--------------------------------------------------------
-- FILE: Nhom5_DataBaseSecurity_FIXED.sql
-- CHAY DUOI QUYEN: SYS AS SYSDBA
--------------------------------------------------------

-- 1. XOA USER VA ROLE CU NEU CO
BEGIN
    FOR r IN (SELECT role FROM dba_roles WHERE role IN ('ROLE_ADMIN', 'ROLE_NHANVIEN')) LOOP
        EXECUTE IMMEDIATE 'DROP ROLE ' || r.role;
    END LOOP;
END;
/
-- Drop user (bao gom ca bang va du lieu)
DROP USER QUANLYKS CASCADE;
-- Drop tablespace
DROP TABLESPACE HOTEL_DATA INCLUDING CONTENTS AND DATAFILES;

-- 2. TAO TABLESPACE
CREATE TABLESPACE HOTEL_DATA
DATAFILE 'hotel_data.dbf' SIZE 100M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED;

-- 3. TAO USER
CREATE USER QUANLYKS IDENTIFIED BY 123456
DEFAULT TABLESPACE HOTEL_DATA
QUOTA UNLIMITED ON HOTEL_DATA;

-- 4. TAO ROLES (QUAN TRONG - BAN THIEU PHAN NAY)
CREATE ROLE ROLE_ADMIN;
CREATE ROLE ROLE_NHANVIEN;

-- 5. CAP QUYEN CHO USER QUANLYKS
GRANT CONNECT, RESOURCE TO QUANLYKS;
GRANT CREATE VIEW TO QUANLYKS;
GRANT CREATE PROCEDURE TO QUANLYKS;
GRANT CREATE TRIGGER TO QUANLYKS;
GRANT CREATE SEQUENCE TO QUANLYKS;
GRANT CREATE ANY CONTEXT TO QUANLYKS;
GRANT EXECUTE ON DBMS_CRYPTO TO QUANLYKS;
GRANT EXECUTE ON DBMS_RLS TO QUANLYKS;

-- Cap quyen quan ly Role cho QUANLYKS (de grant cho user khac)
GRANT GRANT ANY ROLE TO QUANLYKS;
GRANT ADMINISTER DATABASE TRIGGER TO QUANLYKS;

-- 6. OLS (Oracle Label Security)
-- Luu y: Chi chay neu Database da cai OLS. Neu khong se bao loi.
-- BEGIN
--     LBACSYS.CONFIGURE_OLS;
-- END;
-- /

-- T?o Context tên là QLKS_APP và ch? cho phép Package PKG_SECURITY thao tác
CREATE OR REPLACE CONTEXT QLKS_APP USING QUANLYKS.PKG_SECURITY;